# Generated by Django 2.2.28 on 2025-03-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(help_text='Category of item', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.Category'),
        ),
    ]
