# Generated by Django 2.2.28 on 2025-03-12 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 11, 22, 14, 582296)),
        ),
    ]
