# Generated by Django 2.2.28 on 2025-03-13 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_listing_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='app.Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 14, 16, 56, 680617)),
        ),
    ]
