# Generated by Django 2.2.28 on 2025-03-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_listing_image_media'),
        ('app', '0005_auto_20250313_1416'),
    ]

    operations = [
    ]
