# Generated by Django 4.2.20 on 2025-03-17 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_bid_id_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 24, 15, 52, 45, 867850)
            ),
        ),
    ]
